# the official unprivileged Nginx image nginxinc/nginx-unprivileged, 
# which is specifically pre-configured to run as a non-root user out of the box.

FROM nginxinc/nginx-unprivileged:alpine 
COPY index.html /usr/share/nginx/html/
EXPOSE 8080