apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vanguardyouth-dr-tls
  namespace: istio-ingress # MUST match the DR Helm gateway release namespace!
spec:
  # Secret name mounted by Istio Ingress Gateway in DR
  secretName: vanguardyouth-dr-tls-cert
  issuerRef:
    name: production-cluster-issuer # Requires DNS-01 route53 solver for root & wildcards
    kind: ClusterIssuer
  dnsNames:
    - "vanguardyouth.store"
    - "*.vanguardyouth.store" # Matches api.vanguardyouth.store, app.vanguardyouth.store, etc.